---
# - name: Set MySQL root password before installing
#   debconf:
#     name: 'mariadb-server'
#     question: 'mysql-server/root_password'
#     value: "{{ mysql_root_password | quote }}"
#     vtype: 'password'
#   become: true
#   tags: mysql_installation
# - name: Confirm MySQL root password before installing
#   debconf:
#     name: 'mariadb-server'
#     question: 'mysql-server/root_password'
#     value: "{{ mysql_root_password | quote }}"
#     vtype: 'password'
#   become: true
#   tags: mysql_installation
- name: Install mariadb-server
  apt: pkg={{ item }} state=latest
  become: true
  with_items:
    - mariadb-server
    - python-mysqldb
  tags: mysql_installation

- name: Copy "my.cnf" as root
  template:
    src: templates/my.cnf
    dest: /etc/mysql/my.cnf
    owner: root
    mode: 0644
  become: true
  tags: mysql_installation

- name: Update MySQL root password for all root accounts
  mysql_user:
    name: root
    host: localhost
    password: "{{ mysql_root_password }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
  tags: mysql_installation

# - name: Disallow root login remotely
#   command: 'mysql -NBe "{{ item }}"'
#   with_items:
#     - DELETE FROM mysql.user WHERE User=root AND Host NOT IN ('localhost', '127.0.0.1', '::1')
#   changed_when: false
#   tags: mysql_safety
- name: Remove all anonymous user accounts.
  mysql_user:
     name: ""
     host_all: yes
     state: absent
     login_user: root
     login_password: "{{ mysql_root_password }}"
  tags: mysql_safety
- name: Remove MySQL test database.
  mysql_db:
    name: test
    state: absent
    login_user: root
    login_password: "{{ mysql_root_password }}"
  tags: mysql_safety

- name: Restart the MySQL service to apply changes
  service: name=mysql state=restarted
  become: true
  tags: mysql_installation

- name: Ensure MySQL is running and starts on boot
  service: name=mysql state=started
  become: true
  tags: mysql_installation
