heat_template_version: 2015-04-30

description: Simple template to deploy a single compute instance

parameters:
  key_name:
    type: string
    label: Key Name
    description: Name of key-pair to be used for compute instance
    default: mykey
  image_id:
    type: string
    label: Image ID
    description: Image to be used for compute instance
    default: Ubuntu14.04_LTS
  flavor:
    type: string
    label: Instance Type
    description: Type of instance (flavor) to be used
    default: m1.tiny
    constraints:
      - allowed_values: [ m1.tiny, m1.small, m1.medium ]
        description: Value must be one of m1.tiny, m1.small or m1.medium.
  public_network:
    type: string
    description: Public network name.
    default: public
  # private_network:
  #   type: string
  #   label: Private network name or ID
  #   description: Network to attach instance to.
  #   default: morse-net
  # private_subnet:
  #       type: string
  #       label: Private network name or ID
  #       description: Network to attach instance to.
  #       default: 828b4c98-2aef-48e1-9bd2-e0179258d863
  #       # default: morse-subnet

resources:
  private_network:
        type: OS::Neutron::Net
        properties:
          name: morse-net

  private_subnet:
        type: OS::Neutron::Subnet
        properties:
          name: morse-subnet
          network_id: { get_resource: private_network }
          cidr: 192.168.0.0/24
          dns_nameservers: [ 8.8.4.4 ]
          ip_version: 4
          # gateway_ip: 172.16.2.1

  router_morse:
        type: OS::Neutron::Router
        properties:
          external_gateway_info:
                network: { get_param: public_network }

  router_morse_interface:
        type: OS::Neutron::RouterInterface
        properties:
          router_id: { get_resource: router_morse }
          subnet_id: { get_resource: private_subnet }

  morse_sg:
    type: OS::Neutron::SecurityGroup
    properties:
      rules:
        - protocol: icmp
          remote_ip_prefix: 0.0.0.0/0
        - protocol: tcp
          remote_ip_prefix: 0.0.0.0/0
          port_range_min: 80
          port_range_max: 80
        - protocol: tcp
          remote_ip_prefix: 0.0.0.0/0
          port_range_min: 443
          port_range_max: 443
        - protocol: tcp
          remote_ip_prefix: 0.0.0.0/0
          port_range_min: 22
          port_range_max: 22
        - protocol: tcp
          remote_ip_prefix: 0.0.0.0/0
          port_range_min: 5000
          port_range_max: 5000

  instance_port:
    type: OS::Neutron::Port
    properties:
      network: { get_resource: private_network }
      security_groups:
        - { get_resource: morse_sg }
      fixed_ips:
        - subnet_id: { get_resource: private_subnet }

  morse_server:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: key_name }
      image: { get_param: image_id }
      flavor: { get_param: flavor }
      networks:
        - port: { get_resource: instance_port }
      user_data_format: SOFTWARE_CONFIG
      # user_data:
      #   get_file: initial_config.sh
      # user_data: |
      #   #!/bin/bash
      #   sudo apt-get update
      #   sudo apt-get -y dist-upgrade
      #   sudo apt-get -y install git
      #   git clone https://github.com/AlvaroRuizDelgado/Morse.git
      #   . Morse/install.sh
      #   . Morse/run_flask
      #   # ...

  config:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config:
        get_file: initial_config.sh

  deployment:
    type: OS::Heat::SoftwareDeployment
    properties:
      config:
        get_resource: config
      server:
        get_resource: morse_server

  floating_IP:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param : public_network }

  association:
    type: OS::Neutron::FloatingIPAssociation
    properties:
      floatingip_id: { get_resource: floating_IP }
      port_id: { get_resource: instance_port }
      # port_id: {get_attr: [morse_server, addresses, {get_resource: private_network}, 0, port]}

outputs:
  private_ip:
    description: The private IP address of the deployed instance
    value: { get_attr: [morse_server, first_address] }
  public_ip:
    description: Public IP address of the deployed instance
    value: { get_attr: [ floating_IP, floating_ip_address ] }
