---
- hosts: morse
  vars:
    repo_url: https://github.com/AlvaroRuizDelgado/Morse.git
    repo_branch: master
    webapp_dir: /home/ubuntu
    webapp_name: Morse
    venv: venv
    flask_app: fl_mogi_morse.py

  tasks:
  # - name: Create a test file
  #   file: path=test_file state=touch
  #   tags: debug

  - name: Update the system
    apt: update_cache=yes
    when: ansible_os_family == "Debian"
    become: true
    tags: update
  # - name: Upgrade the distribution
  #   apt: upgrade=dist
  #   when: ansible_os_family == "Debian"
  #   become: true
  #   tags: update

  - name: Install git
    package:
      name: git
      state: latest
    become: true
    tags: git
  - name: Check if the git directory exists
    stat: path={{ webapp_dir }}/{{ webapp_name }}
    register: check_git_path
    tags: git
  - name: Clone the data if it doesn't exist
    git:
      repo: "{{ repo_url }}"
      dest: "{{ webapp_dir }}/{{ webapp_name }}"
      version: "{{ repo_branch }}"
    when: check_git_path.stat.exists == false
    tags: git
  - name: Update the data if it exists
    git:
      repo: "{{ repo_url }}"
      dest: "{{ webapp_dir }}/{{ webapp_name }}"
      version: "{{ repo_branch }}"
      clone: no
    when: check_git_path.stat.exists
    tags: git

  - name: Install virtualenv.
    package:
      name: python-virtualenv
      state: latest
    become: true
    tags: flask
  - name: Virtual environment and install requirements.
    pip:
      name: Flask
      state: latest
      # requirements: "{{ webapp_dir }}/{{ webapp_name }}/requirements.txt"
      virtualenv: "{{ webapp_dir }}/{{ webapp_name }}/{{ venv }}/"
      # virtualenv_python: python2.7
    tags: flask
  - name: Run flask
    shell:
      nohup venv/bin/flask run --host=0.0.0.0 > flask.log 2>&1 &
    environment:
      FLASK_APP: "{{ flask_app }}"
    args:
      chdir: Morse/
    tags: flask
